language: c
compiler: gcc

# We need to be root to install the dependencies
sudo: true


before_install:
 # Refreshing the APT cache doesn't hurt
 - sudo apt-get update

install:
 # Install dependencies from the bash script
 - sudo ./install_deps.sh


script:
 - make
